version: '2.4'

services:

  php56:
    build: ./5.6
    image: doanbaanh/php-fpm:5.6

  php73:
    build: ./7.3
    image: doanbaanh/php-fpm:7.3

  php74:
    build: ./7.4
    image: doanbaanh/php-fpm:7.4

  php80:
    build: ./8.0
    image: doanbaanh/php-fpm:8.0

  php56-dev:
    build: ./5.6/dev
    image: doanbaanh/php-fpm:5.6-dev

  php73-dev:
    build: ./7.3/dev
    image: doanbaanh/php-fpm:7.3-dev

  php74-dev:
    build: ./7.4/dev
    image: doanbaanh/php-fpm:7.4-dev

  php80-dev:
    build: ./8.0/dev
    image: doanbaanh/php-fpm:8.0-dev

  php56-dev-xdebug:
    build: ./5.6/dev-xdebug
    image: doanbaanh/php-fpm:5.6-dev-xdebug

  php73-dev-xdebug:
    build: ./7.3/dev-xdebug
    image: doanbaanh/php-fpm:7.3-dev-xdebug

  php74-dev-xdebug:
    build: ./7.4/dev-xdebug
    image: doanbaanh/php-fpm:7.4-dev-xdebug

  php80-dev-xdebug:
    build: ./8.0/dev-xdebug
    image: doanbaanh/php-fpm:8.0-dev-xdebug
