version: "3.9"

services:
  php-5.6-dev:
    image: "doanbaanh/php-fpm:5.6-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=5.6"

  php-7.3-dev:
    image: "doanbaanh/php-fpm:7.3-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=7.3"

  php-7.4-dev:
    image: "doanbaanh/php-fpm:7.4-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=7.4"

  php-8.0-dev:
    image: "doanbaanh/php-fpm:8.0-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=8.0"
  
  php-8.1-dev:
    image: "doanbaanh/php-fpm:8.1-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=8.1"
  
  php-8.2-dev:
    image: "doanbaanh/php-fpm:8.2-dev"
    build:
      context: "./dev"
      args:
        - "PHP_IMG_TAG=8.2"
  